### ISSUE TITLE
Decimal Interpolation

### ISSUE THREAD

**Issue by batiati** [batiati/mustache-zig#7]
We fail with [this test from mustaches spec](https://github.com/mustache/spec/blob/f794f93d2e1bee7d5ec5a6a197b107cc58f12e05/specs/interpolation.yml#L86)

```yaml
- name: Basic Decimal Interpolation
    desc: Decimals should interpolate seamlessly with proper significance.
    data: { power: 1.210 }
    template: '"{{power}} jiggawatts!"'
    expected: '"1.21 jiggawatts!"'
```

Suggestions:

- Implement a custom formatter for floats
- Introduce a new configuration for max float precision, preventing from rendering things like `1.21000345698`
- Maybe waiting for [Ryu floating point printing](https://github.com/ziglang/zig/issues/1299)
